### ISSUE TITLE
Color instability for ws2812B leds on RPI4B

### ISSUE THREAD

**Issue by aleksas** [hepingood/ws2812b#22]
### Version

1.0.0

### Describe the bug

On Raspbery Pi 4b modified code to flicker in a loop for a default color (RED). Most of the times color goes from red to turned off, but sometimes all leds shive white color for some cicles and then go back to flickering between red and none.

### Reproduce

Code changes [are provided in a form of a patch](https://github.com/hepingood/ws2812b/pull/21)

App executed using following command:
`ws2812b -e write --number 24`

### Expected behavior

Stable flickering between RED and turning off

**Comment by hepingood** [comment]
It may be related to the timing reset signal, and we have fixed this issue. You can pull and test again.

**Comment by aleksas** [comment]
Issues still present after update

https://github.com/hepingood/ws2812b/assets/594470/1a32dad7-b157-4c25-9def-b85d3a1f7f47

It may also be related to [this issue/feature](https://github.com/raspberrypi/linux/issues/3381) in RPI itself
